const express = require("express");
const router = express.Router();
const dbController = require("../../controllers/db");
const goalController = require("../../controllers/goal");
const passport = require("../../config/passport");
router.post("/", (req, res) => dbController.create(req, res, "goals"));
router.delete("/:goalid", (req, res) => dbController.remove(req, res, "goals"));
router.put("/", passport.authenticateJWT, goalController.update);
router.get("/", passport.authenticateJWT, goalController.all);
module.exports = router;
